### PR TITLE
add trimmomatic module + specify qual_trim

### LINKED ISSUE #8: Trimmomatic
https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/52181c51d634128a84a774838a61c1bae0acbf23/WDL/ctat_VIF.wdl#L160-L168

https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/52181c51d634128a84a774838a61c1bae0acbf23/WDL/ctat_VIF.wdl#L324

### PR DESCRIPTION
**Pull request by alyssa-ab**
## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralintegration/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/viralintegration _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by alyssa-ab** [comment]
Added trimmomatic and runs successfully. Linting fails. If we're concerned about this, I'd love some feedback in that area. 

Main question with linting failure would be the local module not matching the remote since I needed to specify the qual_trim variable for a successful run. Is there a more proper way to define that in the workflow?
`    def qual_trim = task.ext.args2 ?: 'ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36'
`

**Comment by edmundmiller** [comment]
> Linting fails. If we're concerned about this, I'd love some feedback in that area.

I'm not concerned about the pipeline ones, those would mostly be fixed with template update. The module lint, I am somewhat concerned by, but I'm pretty it's also a problem with the template not being updated (and those aren't triggered automatically because this isn't under the nf-core GitHub org). I just eyeballed it, and they looked the same, so let's not worry about that either.

> Is there a more proper way to define that in the workflow?

There is! Add a TRIMMOMATIC entry in  https://github.com/nf-osi/viralintegration/blob/dev/conf/modules.config, and you can see [the settings the original pipeline used ](https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/52181c51d634128a84a774838a61c1bae0acbf23/WDL/ctat_VIF.wdl#L336) Which I'm not sure works for single ended reads, but we're just going for duplication, and then we can fix it/replace it.

**Comment by alyssa-ab** [comment]
>  Add a TRIMMOMATIC entry in https://github.com/nf-osi/viralintegration/blob/dev/conf/modules.config, and you can see [the settings the original pipeline used ](https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/52181c51d634128a84a774838a61c1bae0acbf23/WDL/ctat_VIF.wdl#L336) Which I'm not sure works for single ended reads, but we're just going for duplication, and then we can fix it/replace it.

Awesome, got that added. The module no longer fails linting (just the pipeline issues) and the run still works! Let me know if anything else looks like it should be adjusted before we merge.

**Comment by edmundmiller** [comment]
Awesome work!

I just remembered, let's add trimmomatic to multiqc! https://multiqc.info/docs/#trimmomatic

```nextflow
    ch_multiqc_files = ch_multiqc_files.mix(TRIMMOMATIC.out.log.collect{it[1]}.ifEmpty([]))
```

or something should to do!

**Comment by alyssa-ab** [comment]
Got it! I believe I amended that onto the last commit if all went well

**Review by edmundmiller — APPROVED** [review]
Awesome work!

**Comment by edmundmiller** [comment]
Closes #8

**Pull request merged**
