### PR TITLE
Add viral_fasta and index

### PR DESCRIPTION
**Pull request by alyssa-ab**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralintegration/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/viralintegration _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by allaway — APPROVED** [review]
Looking good, thanks for this! I made some minor documentation change suggestions here: https://github.com/alyssa-ab/viralintegration/pull/1

It's not clear to me why the Prettier CI is failing, but I don't think that is too big of a deal this early on.

**Comment by allaway** [comment]
Oh, I see it's just a format check, it's not actually running Prettier to reformat.

**Comment by allaway** [comment]
Alrighty, ran `prettier` and added those changes to https://github.com/alyssa-ab/viralintegration/pull/1 as well.

**Review by edmundmiller — APPROVED** [review]
LGTM!

**Pull request merged**
